version: '3.8'
services:
  credit-risk-model:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./model_artifact:/app/model_artifact
      - ./src:/app/src
    environment:
      - PORT=8080
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  dashboard:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - credit-risk-model

  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
