apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-risk-model
  labels:
    app: credit-risk-model
spec:
  replicas: 3
  selector:
    matchLabels:
      app: credit-risk-model
  template:
    metadata:
      labels:
        app: credit-risk-model
    spec:
      containers:
      - name: credit-risk-model
        image: ghcr.io/your-org/credit-risk-model:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: credit-risk-model-service
spec:
  selector:
    app: credit-risk-model
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
